### ISSUE TITLE
Request 32bit kernel Rpi4

### ISSUE THREAD

**Issue by retro24** [HinTak/RaspberryPi-Dev#2]
Hello,is it possible to release a 32bit kernel for Raspberry pi 4  for berryboot since many things are not working in the 64bit kernel

thank you

**Comment by HinTak** [comment]
@retro24 there is a 32-bit build - https://github.com/HinTak/berryboot/releases/tag/berryboot-20201109-pi0123%2Brespeaker - somebody had some problems with it though. Give it a try and let me know. If it works for you, please feel free to click the donate link.

**Comment by retro24** [comment]
i tried it,it booted to the berryboot install menu,but the mouse and the keyboard were not working
i tried two different mouse and keyboards but nothing worked

**Comment by HinTak** [comment]
That's USB mouse/keyboard, right? I'll have a look sometimes.

**Comment by retro24** [comment]
yes usb i tried both wired and wireless they did not work

**Comment by HinTak** [comment]
Okay. I'll find some time to have a look.

**Comment by retro24** [comment]
ok thanks

**Comment by HinTak** [comment]
@retro24 I can you post the usb vendor and product ids of your keyboards/mouses? It is unlikely you have something too exotic, but I can check what drivers they are supposed to be using. 

If you have another linux system (desktop or pi) , when you plug them in, in `dmesg`, there should be a few lines at the bottom about new devices found with `idVendor=... idProduct=...`. Alternatively `lsusb` should do too. You can find the same info in Windows' device manager etc.

**Comment by retro24** [comment]
all the info i could find is that

dev 1 class=root_hub driver=xhci_hcd/4p, 5000M
dev 1 class=root_hub driver=xhci_hcd/1p, 480M
port 1 dev 2, if 0 class=Hub, driver=hub/4p, 480p
port4 dev 3 if 0 class=Human Interface Device, Driver=usbhid, 1.5M
port4 dev 3 if 1 class=Human Interface Device, Driver=usbhid, 1.5M

**Comment by HinTak** [comment]
I don't think you need usbview itself, but this page at the bottom https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/usbview explains how to get to usb info in the device manager. The vendor id / product id may be shortened to `vid=/pid=` and given as `instance id`.

**Comment by retro24** [comment]
yes i went there i dont see any vendor id or vid/pid  i only found a hid compliant mouse/keyboard 

keyboard.inf:MS_KBD.NTx86:HID_Keyboard_Inst:6.1.7601.17514::hid_device_system_keyboard
msmouse.inf:MSMfg.NTx86:HID_Mouse_Inst:6.1.7600.16385::hid_device_system_mouse

Another thing now the only difference from the original berryboot and yours in this version "berryboot-20201108-pi0123.zip"

is the updated kernel v5.4.81 ??

so i can use it as i  use the normal berryboot ??

**Comment by HinTak** [comment]
I asked because the usual kernel tree ships about a dozen hid drivers.

I don't personally use berryboot - the build was done as a request to bundle the respeaker drivers. The person eventually went with the 64-bit build. I tried to update the 32-bit build to be functionally the same as the 64-bit one. It should be closer to the 64-bit build than to the previous 32-bit build. It is possible I missed something.

**Comment by HinTak** [comment]
New 32-bit build -
https://github.com/HinTak/berryboot/releases/tag/berryboot-20210127-pi4%2Brespeaker

New 64-bit build, this also contains a workaround for a certain type of driver problems - it may solve whatever "...many things are not working..." issue:
https://github.com/HinTak/berryboot/releases/tag/berryboot-20210127-pi64%2Brespeaker
 
BTW, I don't think it is appropriate for you to file a issue in one of my personal repos, to ask for help on software I don't maintain. Please do not do that. It is barely appropriate to CC @ me in the upstream issue, which quite wrongly, you also omit to mention you already filed.

If either of the new builds work, please click the donate links at https://hintak.github.io/ .

**Comment by actraiser30** [comment]
Hello any change that you can add to berryboot NTFS support so i can use a flash drive or a hard disk in NTFS format to copy images to berryboot or save modified images to the flash drive ?

**Comment by HinTak** [comment]
@actraiser30 it has been almost 2 decades that ntfs on Linux works via fuse (file system in userland) and fuse has been enabled for equally long as standard on all modern Linux systems. You just need to install the ntfs-3g package on the distribution side. There is nothing to be done on berryboot, as fuse is included as standard . This has been the case for about 15 years!

Click donate at https://hintak.github.io if you wish.

**Comment by actraiser30** [comment]
but still berryboot does not see ntfs drives..

**Comment by HinTak** [comment]
@actraiser30 as I wrote, ntfs is all in useland / distribution side. If you are using raspbian with berryboot, you should install ntfs-3g on raspbian; same go with berryboot with archlinux, etc. You install the archlinux ntfs-3g package, etc. I think once you have ntfs-3g for raspbian or ntfs-3g for archlinux or the distro you use berryboot with, it should auto-detect. There is nothing more needed on berryboot.

**Comment by actraiser30** [comment]
ntfs works in any OS with berryboot but not in the edit menu option that you can add operating systems from a hard disk or a flash drive or save a modified os to a hard drive it only see fat32 this is what i mean not the os

**Comment by HinTak** [comment]
@actraiser30 you did not read above? "BTW, I don't think it is appropriate for you to file a issue in one of my personal repos, to ask for help on software I don't maintain. Please do not do that. It is barely appropriate to CC @ me in the upstream issue". It is a limitation of berryboot to be able to boot from and see a limited list of file system at boot time. This is a general Linux limitation too. I shall insist that you click donate at https://hintak.github.io before you write anything.

If Linux (in general) cannot boot from a particular file system type, there is no point in reading or saving boot-filesystems to those.
