### ISSUE TITLE
update kernel

### ISSUE THREAD

**Issue by actraiser30** [HinTak/RaspberryPi-Dev#4]
Hi there is it possible to update the 32bit version of your berryboot so it has updated firmware/kernel drivers?

https://github.com/HinTak/berryboot/releases

last update for the 32Bit is from 20210127

thank you

**Comment by HinTak** [comment]
@actraiser30 new build https://github.com/HinTak/berryboot/releases/tag/berryboot-20210805-pi0123%2Brespeaker , updated to the current upstream release 1.20210805 , 5.10.52 . Some people said the last one did not work; it is just provided as is... If it works for you, please consider donating at the bottom of https://hintak.github.io/ .

**Comment by actraiser30** [comment]
thanks if its possible to make also an updated 32Bit version for RPi4 will be great thanks a lot

**Comment by HinTak** [comment]
@actraiser30 a lot of people don't understand: on a smooth running linux system most time is spent on serving user (as it should), so it does not matter that the kernel is "generic", as very little time is spent on running the kernel itself. So in other words, I won't make any special builds, as there is no point.
