### ISSUE TITLE
BB repo update

### ISSUE THREAD

**Issue by actraiser30** [HinTak/RaspberryPi-Dev#6]
Hello there all good ??

Sorry i dont know were else to post so i can contact you,

Im trying to build berryboot from your github repo without success 

I understand that some files are outdated in your github/berryboot

is it possible to update/upgrade your github repo/files of berryboot: https://github.com/HinTak/berryboot

so the building/compiling of Berryboot wont fail???

Thanks in advance

**Comment by HinTak** [comment]
The correct way is file at berryboot and @ me. Sorry, I don't have any plan of spending any time on it.

**Comment by actraiser30** [comment]
i did that no use,anyway bye

**Comment by HinTak** [comment]
I already said no. Stop abusing my repo.
